### PR TITLE
Use CompatHelper.jl with precommit_hook

### PR DESCRIPTION
**Pull request by tkf**
ref https://github.com/bcbi/CompatHelper.jl/issues/29

### CODE REVIEW

**Comment by DilumAluthge** [comment]
Don't merge this yet

**Comment by DilumAluthge** [comment]
I'm going to merge `da/precommit_hook` into `master`, and then delete the `da/precommit_hook` branch.

**Comment by tkf** [comment]
Thanks for the warning :)

Do you know how to manually start an action? It'd be nice if we can check if it works as expected.

**Comment by DilumAluthge** [comment]
Yeah.

In your workflow file, replace this content:
```yaml
on:
  schedule:
    - cron: '00 * * * *'
```

With this:
```
on:
  schedule:
    - cron: '00 * * * *'
  issues:
    types: [opened, reopened]
```

Then create a dummy issue. You can close and re-open the issue repeatedly, and this will trigger the action.

Just be aware that you cannot run an action more frequently than once every five minutes, no matter what.

**Comment by tkf** [comment]
Thanks! I guess I have to merge it to `master` to try it out?

**Comment by DilumAluthge** [comment]
Yeah

**Comment by DilumAluthge** [comment]
Btw the feature is now implemented in CompatHelper master. Give it a try.

**Comment by DilumAluthge** [comment]
https://github.com/tkf/Kaleido.jl/commit/e85db6804f748083e60997656c2f3f9a6d94652a/checks?check_suite_id=297682432

**Comment by DilumAluthge** [comment]
Seems like they don't like your YAML file

**Pull request merged**
